name: publish container images
on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: backend repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      # - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login in to quay.io registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build container image and push
        run: ./scripts/publish_container_images.sh